GET http://localhost:3500/pets HTTP/1.1

###
GET http://localhost:3500/pets/1 HTTP/1.1

###
GET http://localhost:3500/pets/99 HTTP/1.1

###
POST http://localhost:3500/pets HTTP/1.1
Content-Type: application/json

{
"id": 4,
"QR": "234wr23ewr2werwer",
"petName": "Arturo",
"ownerName": "Cacho Castaniares",
"phone": "3794566566",
"medicine": "",
"other": ""
}

###
PUT http://localhost:3500/pets/1 HTTP/1.1
Content-Type: application/json

{
   "QR": "r3346789werfg234242sdawerweq3242323rewrwer",
   "petName": "Pelusa",
   "ownerName": "Diego Toronja",
   "phone": "3794592343",
   "medicine": "",
   "other": "",
   "createdAt": null
}

###
DELETE http://localhost:3500/pets/1 HTTP/1.1
